### ISSUE TITLE
Crashes when quickly skipping songs

### ISSUE THREAD

**Issue by tychoregter** [bermudalocket/MeltedCrayons#11]
**Describe the bug**
When quickly skipping through songs in Apple Music the app sometimes crashes.

**To Reproduce**
Just skip through songs quickly, sometimes it doesn’t crash but occasionally it does. 

**Expected behavior**
I should be able to skip through songs without making the app crash.

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: iOS 13.3.1 (checkra1n)

**Comment by zabinga73** [comment]
Also happens to me on spotify, app freezes when skipping songs. Restarting the app twice is required when this happens

iPhone XR
iOS 13.3 (unc0ver)

**Comment by jakeva** [comment]
**Describe the bug**
If you are in a playlist that you do not have downloaded or have poor connection and skip songs very fast, it will eventually cause the app to freeze while playing the incorrect song. Please see video below for more information.

**To Reproduce**
Steps to reproduce the behavior:
1. Have poor connection and/or a non-downloaded playlist
2. Skip songs very quickly
3. Freeze will occur while showing the incorrect song that is playing.

**Expected behavior**
Song should play without issue and the MeltedCrayons tweak should run shortly after the cover displays.

**Videos**
Video 1: https://youtu.be/BulNcoBx--c
Video 2: https://youtu.be/7HSrqu8CeUA

**Smartphone (please complete the following information):**
 - Device: iPhone Xr
 - OS: 13.3

**Additional context**
1. ColorFlow is installed, however, is disabled inside Spotify.
2. This issue still occurs with ColorFlow completely installed.

**Comment by bermudalocket** [comment]
I'm able to reproduce this issue on a vanilla device. The root cause is a bug in the Spotify app. If you switch songs quickly enough, eventually the playing song will come out of sync with the player view and you won't be able to move more than one or two songs in either direction before the buttons disable. I have submitted a bug report to Spotify and will update as necessary.

In the meantime I've added some precautionary measures to reduce the probability of a crash, but unfortunately there's not much I can do until Spotify fixes the issue on their end.
