### ISSUE TITLE
Apples own implementation 

### ISSUE THREAD

**Issue by tychoregter** [bermudalocket/MeltedCrayons#23]
There’s probably a reason this hasn’t been done yet but it seems kinda obvious to me to just use Apple’s own lyrics background, it doesn’t seem completely unreasonable since it’s already there on the regular music player view when your skipping a song while in the lyrics view to a song that doesn’t have a lyrics. That implementation seems to work better and more stable.

**Comment by bermudalocket** [comment]
A few reasons, but mostly because Apple's implementation uses MetalKit which is inherently more resource-hungry than my version. This means worse battery life and a higher operating temperature. I wanted to create my own implementation to both offer something unique, something that wouldn't eat your battery life, and something that can run well on older phones.
